### ISSUE TITLE
The CMMD value is different from the example

### ISSUE THREAD

**Issue by feilvvl** [sayakpaul/cmmd-pytorch#3]
Hi, thank you very much for being able to implement CMMD using Pytorch, it definitely helped me a lot!
But when I run the example, the result is different. （**7.717** vs **7.696**）
![image](https://github.com/sayakpaul/cmmd-pytorch/assets/65100730/0d8c34a5-b2e2-46f6-ad4a-619efe083dd5)
I wonder if there is a mistake in my environment. My cuda version is release 11.1, torch version is 1.10.2+cu111, can you give me more results about the configuration? For example, torch version, cuda version, etc. If you provide it in detail, I would appreciate it.

**Comment by sayakpaul** [comment]
I am on PyTorch 2.0 and CUDA 12.0. I ran my tests on A100.

**Comment by feilvvl** [comment]
> I am on PyTorch 2.0 and CUDA 12.0. I ran my tests on A100.
That is great! I have tried your configuration and got the right answer 7.696! Thank you a lot!
